# Generated by Django 2.2 on 2020-01-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('profile_pic_url', models.TextField()),
                ('bio', models.TextField()),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('is_good_boy', models.BooleanField(default=False)),
                ('birthday', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete='CASCADE', related_name='dogs', to='app.User')),
                ('tricks', models.ManyToManyField(related_name='dogs_with_tricks', to='app.Trick')),
            ],
        ),
    ]
